apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: add-ing
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: add.cloudpunk.shop
    http:
      paths:
      - backend:
          service:
            name: add-service
            port:
              number: 80
        path: "/"
        pathType: Prefix

